### PR TITLE
Add runtime_identifier to entity description

### PR DESCRIPTION
**Pull request by Xterionix**
Did this so I can use it in the diagnoser, hopefully the right way to go about it

### CODE REVIEW

**Review by DaanV2 — APPROVED** [review]
:+1:

**Comment by DaanV2** [comment]
Released a new version: v1.20.71-14

**Comment by DaanV2** [comment]
You can use npm link with: https://github.com/Blockception/bc-mono-minecraft-dev and develop on both :)

**Comment by Xterionix** [comment]
I did try using the mono repo but I got
Cloning into 'C:\Users\admin\Downloads\bc-mono-minecraft-dev'...
remote: Enumerating objects: 451, done.        
remote: Counting objects: 100% (38/38), done.        
remote: Compressing objects: 100% (19/19), done.        
Receiving objects: 100% (451/451), 153.21 KiB | 1.58 MiB/s, done.
remote: Total 451 (delta 28), reused 19 (delta 19), pack-reused 413        
Resolving deltas: 100% (221/221), done.
      5 [main] sh (10552) C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1351408/0x1201408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 529 dofork: child -1 - forked process 10552 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1477642 [main] sh 529 dofork: child -1 - forked process 2356 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
     56 [main] sh (7564) C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1351408/0x1141408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3944116 [main] sh 529 dofork: child -1 - forked process 7564 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (11224) C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1351408/0x1171408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
8397798 [main] sh 529 dofork: child -1 - forked process 11224 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      1 [main] sh (8532) C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1351408/0x1171408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
17177451 [main] sh 529 dofork: child -1 - forked process 8532 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\admin\AppData\Local\GitHubDesktop\app-3.3.11\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by Xterionix** [comment]
No idea what cgywin is

**Comment by DaanV2** [comment]
Hmm all I can find is a bug report on github desktop itself.

Does it work manually? (with git clone https://github.com/Blockception/bc-mono-minecraft-dev.git --recurse-submodules)

**Comment by Xterionix** [comment]
It does not

**Comment by Xterionix** [comment]
Cloning into 'bc-mono-minecraft-dev'...
remote: Enumerating objects: 453, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 453 (delta 29), reused 19 (delta 19), pack-reused 413
Receiving objects: 100% (453/453), 154.35 KiB | 759.00 KiB/s, done.
Resolving deltas: 100% (222/222), done.
      0 [main] sh 7 dofork: child -1 - forked process 9640 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1392414 [main] sh 7 dofork: child -1 - forked process 3412 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
3979678 [main] sh 7 dofork: child -1 - forked process 9152 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
      6 [main] sh 11 child_copy: dll data read copy failed, 0xDE5000..0xDF2010, done 0, windows pid 3528, Win32 error 299
8534529 [main] sh 7 dofork: child -1 - forked process 3528 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
      5 [main] sh 12 child_copy: dll data read copy failed, 0xDD5000..0xDE2010, done 0, windows pid 8272, Win32 error 299
16972818 [main] sh 7 dofork: child -1 - forked process 8272 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by Xterionix** [comment]
Turns out it was an issue with my antivirus. Do I need to run `npm ci` in each of those directories?

**Comment by DaanV2** [comment]
yes, or just the projects you want to test

**Pull request merged**
